# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build
      run: swift build
    - name: Deploy
      run: swift run HarryDayBlog --deploy
    - name: Archive Output
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: Output/
